spring:
  datasource:
    url: jdbc:sqlserver://javatechiedbs.database.windows.net:1433;database=javatechiedb;user=javatechiedbs@javatechiedbs;password=Satya0101;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect
      
     

server:
  port: 9191